spring.application.name=ms-catalogo
server.port=8081

# Conexión a su propia base de datos independiente
spring.datasource.url=jdbc:mysql://localhost:3306/db_pedidos?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect